events {}

http {
    upstream forum_backend {
        # En Swarm, le nom du service "app" résout vers les IPs des replicas
        server app:5000;
        
        # Pour le Blue-Green, on pourrait alterner entre :
        # server app_blue:5000;
        # server app_green:5000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://forum_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Timeout pour éviter de rester bloqué sur une instance en cours de rolling update
            proxy_connect_timeout 5s;
            proxy_read_timeout 60s;
        }
    }
}